import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1767384027398 implements MigrationInterface {
    name = 'InitialSchema1767384027398'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "organizations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(200) NOT NULL, "nit" character varying(50) NOT NULL, "description" text, "address" character varying(500), "phone" character varying(50), "email" character varying(200), "logoUrl" character varying(500), "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_9b7ca6d30b94fef571cff876884" UNIQUE ("name"), CONSTRAINT "UQ_9577eaa355490cc4f48582b8780" UNIQUE ("nit"), CONSTRAINT "PK_6b031fcd0863e3f6b44230163f9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."users_status_enum" AS ENUM('active', 'inactive', 'suspended')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" character varying, "updated_by" character varying, "deletedAt" TIMESTAMP, "names" character varying(50) NOT NULL, "lastNames" character varying(50) NOT NULL, "email" character varying(100) NOT NULL, "username" character varying(30) NOT NULL, "ci" character varying(15) NOT NULL, "password" character varying(255) NOT NULL, "phone" character varying(20), "address" character varying(200), "image" character varying(500), "status" "public"."users_status_enum" NOT NULL DEFAULT 'active', "organizationId" uuid, "roles" text NOT NULL DEFAULT '', CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"), CONSTRAINT "UQ_eff3cf686729ac337fe991de64f" UNIQUE ("ci"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "standards" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "templateId" uuid NOT NULL, "parentId" uuid, "code" character varying(50) NOT NULL, "title" character varying(200) NOT NULL, "description" text, "order" integer NOT NULL, "level" integer NOT NULL DEFAULT '1', "isAuditable" boolean NOT NULL DEFAULT true, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_cb084ce5e29cc74efe0befbefa8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "templates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "description" text, "version" character varying(20), "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_5624219dd33b4644599d4d4b231" UNIQUE ("name"), CONSTRAINT "PK_515948649ce0bbbe391de702ae5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "maturity_levels" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "frameworkId" uuid NOT NULL, "numericValue" numeric(10,2) NOT NULL, "displayValue" character varying(50) NOT NULL, "name" character varying(200) NOT NULL, "shortName" character varying(50), "minRange" numeric(10,2), "maxRange" numeric(10,2), "weight" numeric(5,4), "score" numeric(10,2) NOT NULL DEFAULT '0', "description" text, "observations" text, "recommendations" text, "criteria" text, "implementationGuidance" text, "requiredEvidence" jsonb, "suggestedActions" text, "color" character varying(20), "icon" character varying(10), "order" integer NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_81c8def76639c01612a78d88f24" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."frameworks_frameworktype_enum" AS ENUM('maturity', 'compliance', 'assessment', 'risk')`);
        await queryRunner.query(`CREATE TYPE "public"."frameworks_scoringtype_enum" AS ENUM('discrete', 'percentage', 'binary', 'weighted', 'custom')`);
        await queryRunner.query(`CREATE TABLE "frameworks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "description" text, "frameworkType" "public"."frameworks_frameworktype_enum" NOT NULL DEFAULT 'maturity', "scoringType" "public"."frameworks_scoringtype_enum" NOT NULL DEFAULT 'discrete', "minValue" numeric(10,2) NOT NULL DEFAULT '0', "maxValue" numeric(10,2) NOT NULL DEFAULT '5', "allowDecimals" boolean NOT NULL DEFAULT false, "useWeights" boolean NOT NULL DEFAULT false, "version" character varying(20), "methodology" text, "author" character varying(100), "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_dfaedaffdb18492a02a1f367ac4" UNIQUE ("name"), CONSTRAINT "PK_23e178ce62668c9ce2036b7a3c2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."action_plans_status_enum" AS ENUM('borrador', 'pendiente_aprobacion', 'aprobado', 'rechazado', 'en_progreso', 'completado', 'verificado', 'cerrado', 'vencido')`);
        await queryRunner.query(`CREATE TYPE "public"."action_plans_verificationresult_enum" AS ENUM('aprobado', 'rechazado')`);
        await queryRunner.query(`CREATE TABLE "action_plans" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "evaluationId" uuid NOT NULL, "previousActionPlanId" uuid, "action" text NOT NULL, "rootCause" text, "responsibleId" uuid NOT NULL, "dueDate" date NOT NULL, "createdBy" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "status" "public"."action_plans_status_enum" NOT NULL DEFAULT 'borrador', "approvedBy" uuid, "approvedAt" TIMESTAMP, "rejectionReason" text, "implementationEvidence" jsonb NOT NULL DEFAULT '[]', "progressNotes" text, "completedAt" TIMESTAMP, "verifiedBy" uuid, "verifiedAt" TIMESTAMP, "verificationComments" text, "verificationResult" "public"."action_plans_verificationresult_enum", "isActive" boolean NOT NULL DEFAULT true, "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_969b73b0a2c013da5849ac154fb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."evaluations_compliancestatus_enum" AS ENUM('conforme', 'no_conforme_menor', 'no_conforme_mayor', 'observacion', 'no_aplica')`);
        await queryRunner.query(`CREATE TABLE "evaluations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "auditId" uuid NOT NULL, "standardId" uuid NOT NULL, "maturityLevelId" uuid, "previousEvaluationId" uuid, "score" numeric(10,2) NOT NULL DEFAULT '0', "complianceStatus" "public"."evaluations_compliancestatus_enum", "observations" text, "recommendations" text, "findings" text, "comments" text, "evidence" jsonb NOT NULL DEFAULT '[]', "evaluatedBy" uuid, "evaluatedAt" TIMESTAMP, "isCompleted" boolean NOT NULL DEFAULT false, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f683b433eba0e6dae7e19b29e29" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."audits_audittype_enum" AS ENUM('inicial', 'seguimiento', 'recertificacion')`);
        await queryRunner.query(`CREATE TYPE "public"."audits_status_enum" AS ENUM('draft', 'planned', 'in_progress', 'pending_closure', 'closed', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "audits" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(200) NOT NULL, "description" text, "templateId" uuid NOT NULL, "frameworkId" uuid NOT NULL, "auditType" "public"."audits_audittype_enum" NOT NULL DEFAULT 'inicial', "parentAuditId" uuid, "startDate" date NOT NULL, "endDate" date, "status" "public"."audits_status_enum" NOT NULL DEFAULT 'draft', "scope" text, "organizationId" uuid NOT NULL, "leadAuditorId" uuid NOT NULL, "approverId" uuid, "totalScore" numeric(10,2) NOT NULL DEFAULT '0', "progress" numeric(5,2) NOT NULL DEFAULT '0', "closureMetadata" jsonb, "closureApprovedAt" TIMESTAMP, "closureApprovedBy" uuid, "cancellationMetadata" jsonb, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b2d7a2089999197dc7024820f28" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."reports_reporttype_enum" AS ENUM('audit_report', 'compliance_matrix', 'action_plan_summary', 'executive_summary', 'consolidated_report')`);
        await queryRunner.query(`CREATE TYPE "public"."reports_status_enum" AS ENUM('generating', 'completed', 'failed')`);
        await queryRunner.query(`CREATE TABLE "reports" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying(200) NOT NULL, "reportType" "public"."reports_reporttype_enum" NOT NULL, "status" "public"."reports_status_enum" NOT NULL DEFAULT 'generating', "googleDocId" character varying(200), "googleDocUrl" character varying(500), "auditId" uuid, "generatedBy" uuid NOT NULL, "metadata" jsonb NOT NULL DEFAULT '{}', "errorMessage" text, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d9013193989303580053c0b5ef6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_sockets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "socketId" character varying(100) NOT NULL, "rooms" text NOT NULL DEFAULT '', "userAgent" character varying(500), "ipAddress" character varying(45), "connectedAt" TIMESTAMP NOT NULL DEFAULT now(), "disconnectedAt" TIMESTAMP, "lastActivityAt" TIMESTAMP NOT NULL DEFAULT now(), "metadata" jsonb, CONSTRAINT "UQ_df08e747a9512f2b2efc48d0734" UNIQUE ("socketId"), CONSTRAINT "PK_a96faac5df008a0e86d7edad878" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_58384ddc9feb7b48847b371de0" ON "user_sockets" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_479dc2657bf1adbc62eafeea79" ON "user_sockets" ("disconnectedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_df08e747a9512f2b2efc48d073" ON "user_sockets" ("socketId") `);
        await queryRunner.query(`CREATE INDEX "IDX_3c5fa81960370325e6b876fc4e" ON "user_sockets" ("userId", "disconnectedAt") `);
        await queryRunner.query(`CREATE TYPE "public"."notifications_type_enum" AS ENUM('info', 'warning', 'error', 'success')`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_status_enum" AS ENUM('pending', 'sent', 'delivered', 'read')`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "message" text NOT NULL, "type" "public"."notifications_type_enum" NOT NULL DEFAULT 'info', "status" "public"."notifications_status_enum" NOT NULL DEFAULT 'pending', "userId" uuid, "roomId" uuid, "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "readAt" TIMESTAMP, "deliveredAt" TIMESTAMP, CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "rooms" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" character varying, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_48b79438f8707f3d9ca83d85ea0" UNIQUE ("name"), CONSTRAINT "PK_0368a2d7c215f2d0458a54933f2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_rooms" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "roomId" uuid NOT NULL, "joinedAt" TIMESTAMP NOT NULL DEFAULT now(), "leftAt" TIMESTAMP, "role" character varying(50), "metadata" jsonb, CONSTRAINT "UQ_e8eee1d4d0afcce5bcbefbfe999" UNIQUE ("userId", "roomId", "leftAt"), CONSTRAINT "PK_d991d746a02c6e4aebf11f92a33" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b906271d7694fab17ee3dafc68" ON "user_rooms" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_c8d1a67173ad5d70edb48b4425" ON "user_rooms" ("roomId") `);
        await queryRunner.query(`CREATE INDEX "IDX_bb732017e95e2b0b8508a20068" ON "user_rooms" ("leftAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_af5833ffea8a5555e095be3e58" ON "user_rooms" ("roomId", "leftAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_7e45bf4e344436e438691fb0ca" ON "user_rooms" ("userId", "leftAt") `);
        await queryRunner.query(`CREATE TABLE "refresh_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" character varying, "updated_by" character varying, "deletedAt" TIMESTAMP, "token" character varying(500) NOT NULL, "userId" uuid NOT NULL, "expiresAt" TIMESTAMP NOT NULL, "isRevoked" boolean NOT NULL DEFAULT false, "revokedAt" TIMESTAMP, "ipAddress" character varying(45), "userAgent" character varying(500), "replacedByTokenId" uuid, CONSTRAINT "UQ_4542dd2f38a61354a040ba9fd57" UNIQUE ("token"), CONSTRAINT "PK_7d8bee0204106019488c4c50ffa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_610102b60fea1455310ccd299d" ON "refresh_tokens" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_4542dd2f38a61354a040ba9fd5" ON "refresh_tokens" ("token") `);
        await queryRunner.query(`CREATE TABLE "audit_standard_weights" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "auditId" uuid NOT NULL, "standardId" uuid NOT NULL, "weight" numeric(5,2) NOT NULL DEFAULT '1', "justification" text, "category" character varying(100), "displayOrder" integer NOT NULL DEFAULT '0', "configuredBy" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_be7e5bc56727571cb5212afe0f7" UNIQUE ("auditId", "standardId"), CONSTRAINT "PK_44301dc0607ddf6dc674f5a1d03" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "audit_team" ("auditId" uuid NOT NULL, "auditorId" uuid NOT NULL, CONSTRAINT "PK_54e66c9436215e77472f5e50252" PRIMARY KEY ("auditId", "auditorId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_26ee1cd003d3f10d798bae6d74" ON "audit_team" ("auditId") `);
        await queryRunner.query(`CREATE INDEX "IDX_caa5ee7d1945b2514ee9a7ae78" ON "audit_team" ("auditorId") `);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_f3d6aea8fcca58182b2e80ce979" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "standards" ADD CONSTRAINT "FK_805dd318d004cfb5156b1a5ce8d" FOREIGN KEY ("templateId") REFERENCES "templates"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "standards" ADD CONSTRAINT "FK_a9df2d5c058d37a47d59b7a9c34" FOREIGN KEY ("parentId") REFERENCES "standards"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "maturity_levels" ADD CONSTRAINT "FK_2d5ac37a26afd5bfc1d58c1912b" FOREIGN KEY ("frameworkId") REFERENCES "frameworks"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "action_plans" ADD CONSTRAINT "FK_06c2a1fe4646271321bef3b1f2a" FOREIGN KEY ("evaluationId") REFERENCES "evaluations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "action_plans" ADD CONSTRAINT "FK_87f42d8dc20fa6760eb4c739a20" FOREIGN KEY ("previousActionPlanId") REFERENCES "action_plans"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "action_plans" ADD CONSTRAINT "FK_9ce4c090c0cf8181acd56fff5da" FOREIGN KEY ("responsibleId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "action_plans" ADD CONSTRAINT "FK_781f25a1a95eb1563802c556ee2" FOREIGN KEY ("createdBy") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "action_plans" ADD CONSTRAINT "FK_095f93b9802678b465f88f6cdb8" FOREIGN KEY ("approvedBy") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "action_plans" ADD CONSTRAINT "FK_fc7bb94a3eab3b5fa6574a18af5" FOREIGN KEY ("verifiedBy") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "evaluations" ADD CONSTRAINT "FK_e9ec12f8a82a67ce1117f3e1ec7" FOREIGN KEY ("auditId") REFERENCES "audits"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "evaluations" ADD CONSTRAINT "FK_d53cb758081f9b05a5754c61c71" FOREIGN KEY ("standardId") REFERENCES "standards"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "evaluations" ADD CONSTRAINT "FK_52018d85debfdaaed7d7e56eead" FOREIGN KEY ("maturityLevelId") REFERENCES "maturity_levels"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "evaluations" ADD CONSTRAINT "FK_4b84bbb0a6b55324b20407281a4" FOREIGN KEY ("previousEvaluationId") REFERENCES "evaluations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "evaluations" ADD CONSTRAINT "FK_383b689eacf0a6bc4179f4a181a" FOREIGN KEY ("evaluatedBy") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audits" ADD CONSTRAINT "FK_9d388ca6ecd0a7da43c3fe144ee" FOREIGN KEY ("templateId") REFERENCES "templates"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audits" ADD CONSTRAINT "FK_314b932d31c60b010830ab9ae4a" FOREIGN KEY ("frameworkId") REFERENCES "frameworks"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audits" ADD CONSTRAINT "FK_dcdadf36d0fd457e25d79af6e4f" FOREIGN KEY ("parentAuditId") REFERENCES "audits"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audits" ADD CONSTRAINT "FK_59f6393ca7a2c7643fe0368a4d2" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audits" ADD CONSTRAINT "FK_9b5941218ca2351d086da0f2bf3" FOREIGN KEY ("leadAuditorId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audits" ADD CONSTRAINT "FK_02885173f9468ad70bc3fa83bb0" FOREIGN KEY ("approverId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audits" ADD CONSTRAINT "FK_d58456cf2c105337717b5055935" FOREIGN KEY ("closureApprovedBy") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reports" ADD CONSTRAINT "FK_4c2a0a6ff6e975cd6c286afb85a" FOREIGN KEY ("auditId") REFERENCES "audits"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reports" ADD CONSTRAINT "FK_5637094b9b686cf952b17290179" FOREIGN KEY ("generatedBy") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_sockets" ADD CONSTRAINT "FK_58384ddc9feb7b48847b371de0d" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_692a909ee0fa9383e7859f9b406" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_a379f72e89fd5a7cd81a036aae9" FOREIGN KEY ("roomId") REFERENCES "rooms"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_rooms" ADD CONSTRAINT "FK_b906271d7694fab17ee3dafc681" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_rooms" ADD CONSTRAINT "FK_c8d1a67173ad5d70edb48b4425c" FOREIGN KEY ("roomId") REFERENCES "rooms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "FK_610102b60fea1455310ccd299de" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_standard_weights" ADD CONSTRAINT "FK_9f3ff3d8a1a51066554431d0eba" FOREIGN KEY ("auditId") REFERENCES "audits"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_standard_weights" ADD CONSTRAINT "FK_74ddd3ec6a07719ad60c40bcdd4" FOREIGN KEY ("standardId") REFERENCES "standards"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_standard_weights" ADD CONSTRAINT "FK_7df0b61c1f8551f6e99c8378c6c" FOREIGN KEY ("configuredBy") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_team" ADD CONSTRAINT "FK_26ee1cd003d3f10d798bae6d74b" FOREIGN KEY ("auditId") REFERENCES "audits"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "audit_team" ADD CONSTRAINT "FK_caa5ee7d1945b2514ee9a7ae782" FOREIGN KEY ("auditorId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "audit_team" DROP CONSTRAINT "FK_caa5ee7d1945b2514ee9a7ae782"`);
        await queryRunner.query(`ALTER TABLE "audit_team" DROP CONSTRAINT "FK_26ee1cd003d3f10d798bae6d74b"`);
        await queryRunner.query(`ALTER TABLE "audit_standard_weights" DROP CONSTRAINT "FK_7df0b61c1f8551f6e99c8378c6c"`);
        await queryRunner.query(`ALTER TABLE "audit_standard_weights" DROP CONSTRAINT "FK_74ddd3ec6a07719ad60c40bcdd4"`);
        await queryRunner.query(`ALTER TABLE "audit_standard_weights" DROP CONSTRAINT "FK_9f3ff3d8a1a51066554431d0eba"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "FK_610102b60fea1455310ccd299de"`);
        await queryRunner.query(`ALTER TABLE "user_rooms" DROP CONSTRAINT "FK_c8d1a67173ad5d70edb48b4425c"`);
        await queryRunner.query(`ALTER TABLE "user_rooms" DROP CONSTRAINT "FK_b906271d7694fab17ee3dafc681"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_a379f72e89fd5a7cd81a036aae9"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_692a909ee0fa9383e7859f9b406"`);
        await queryRunner.query(`ALTER TABLE "user_sockets" DROP CONSTRAINT "FK_58384ddc9feb7b48847b371de0d"`);
        await queryRunner.query(`ALTER TABLE "reports" DROP CONSTRAINT "FK_5637094b9b686cf952b17290179"`);
        await queryRunner.query(`ALTER TABLE "reports" DROP CONSTRAINT "FK_4c2a0a6ff6e975cd6c286afb85a"`);
        await queryRunner.query(`ALTER TABLE "audits" DROP CONSTRAINT "FK_d58456cf2c105337717b5055935"`);
        await queryRunner.query(`ALTER TABLE "audits" DROP CONSTRAINT "FK_02885173f9468ad70bc3fa83bb0"`);
        await queryRunner.query(`ALTER TABLE "audits" DROP CONSTRAINT "FK_9b5941218ca2351d086da0f2bf3"`);
        await queryRunner.query(`ALTER TABLE "audits" DROP CONSTRAINT "FK_59f6393ca7a2c7643fe0368a4d2"`);
        await queryRunner.query(`ALTER TABLE "audits" DROP CONSTRAINT "FK_dcdadf36d0fd457e25d79af6e4f"`);
        await queryRunner.query(`ALTER TABLE "audits" DROP CONSTRAINT "FK_314b932d31c60b010830ab9ae4a"`);
        await queryRunner.query(`ALTER TABLE "audits" DROP CONSTRAINT "FK_9d388ca6ecd0a7da43c3fe144ee"`);
        await queryRunner.query(`ALTER TABLE "evaluations" DROP CONSTRAINT "FK_383b689eacf0a6bc4179f4a181a"`);
        await queryRunner.query(`ALTER TABLE "evaluations" DROP CONSTRAINT "FK_4b84bbb0a6b55324b20407281a4"`);
        await queryRunner.query(`ALTER TABLE "evaluations" DROP CONSTRAINT "FK_52018d85debfdaaed7d7e56eead"`);
        await queryRunner.query(`ALTER TABLE "evaluations" DROP CONSTRAINT "FK_d53cb758081f9b05a5754c61c71"`);
        await queryRunner.query(`ALTER TABLE "evaluations" DROP CONSTRAINT "FK_e9ec12f8a82a67ce1117f3e1ec7"`);
        await queryRunner.query(`ALTER TABLE "action_plans" DROP CONSTRAINT "FK_fc7bb94a3eab3b5fa6574a18af5"`);
        await queryRunner.query(`ALTER TABLE "action_plans" DROP CONSTRAINT "FK_095f93b9802678b465f88f6cdb8"`);
        await queryRunner.query(`ALTER TABLE "action_plans" DROP CONSTRAINT "FK_781f25a1a95eb1563802c556ee2"`);
        await queryRunner.query(`ALTER TABLE "action_plans" DROP CONSTRAINT "FK_9ce4c090c0cf8181acd56fff5da"`);
        await queryRunner.query(`ALTER TABLE "action_plans" DROP CONSTRAINT "FK_87f42d8dc20fa6760eb4c739a20"`);
        await queryRunner.query(`ALTER TABLE "action_plans" DROP CONSTRAINT "FK_06c2a1fe4646271321bef3b1f2a"`);
        await queryRunner.query(`ALTER TABLE "maturity_levels" DROP CONSTRAINT "FK_2d5ac37a26afd5bfc1d58c1912b"`);
        await queryRunner.query(`ALTER TABLE "standards" DROP CONSTRAINT "FK_a9df2d5c058d37a47d59b7a9c34"`);
        await queryRunner.query(`ALTER TABLE "standards" DROP CONSTRAINT "FK_805dd318d004cfb5156b1a5ce8d"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_f3d6aea8fcca58182b2e80ce979"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_caa5ee7d1945b2514ee9a7ae78"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_26ee1cd003d3f10d798bae6d74"`);
        await queryRunner.query(`DROP TABLE "audit_team"`);
        await queryRunner.query(`DROP TABLE "audit_standard_weights"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4542dd2f38a61354a040ba9fd5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_610102b60fea1455310ccd299d"`);
        await queryRunner.query(`DROP TABLE "refresh_tokens"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7e45bf4e344436e438691fb0ca"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_af5833ffea8a5555e095be3e58"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bb732017e95e2b0b8508a20068"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c8d1a67173ad5d70edb48b4425"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b906271d7694fab17ee3dafc68"`);
        await queryRunner.query(`DROP TABLE "user_rooms"`);
        await queryRunner.query(`DROP TABLE "rooms"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3c5fa81960370325e6b876fc4e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_df08e747a9512f2b2efc48d073"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_479dc2657bf1adbc62eafeea79"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_58384ddc9feb7b48847b371de0"`);
        await queryRunner.query(`DROP TABLE "user_sockets"`);
        await queryRunner.query(`DROP TABLE "reports"`);
        await queryRunner.query(`DROP TYPE "public"."reports_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."reports_reporttype_enum"`);
        await queryRunner.query(`DROP TABLE "audits"`);
        await queryRunner.query(`DROP TYPE "public"."audits_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."audits_audittype_enum"`);
        await queryRunner.query(`DROP TABLE "evaluations"`);
        await queryRunner.query(`DROP TYPE "public"."evaluations_compliancestatus_enum"`);
        await queryRunner.query(`DROP TABLE "action_plans"`);
        await queryRunner.query(`DROP TYPE "public"."action_plans_verificationresult_enum"`);
        await queryRunner.query(`DROP TYPE "public"."action_plans_status_enum"`);
        await queryRunner.query(`DROP TABLE "frameworks"`);
        await queryRunner.query(`DROP TYPE "public"."frameworks_scoringtype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."frameworks_frameworktype_enum"`);
        await queryRunner.query(`DROP TABLE "maturity_levels"`);
        await queryRunner.query(`DROP TABLE "templates"`);
        await queryRunner.query(`DROP TABLE "standards"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_status_enum"`);
        await queryRunner.query(`DROP TABLE "organizations"`);
    }

}
